# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Audio Guide
email: info@lucawyss.com
description: > # this means to ignore newlines until "baseurl:"
  Audio guide de l'évenement *utopie, dystopie, mazzerati*
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://utopie.lucawyss.com" # the base hostname & protocol for your site, e.g. http://example.com
audio_path: "/audio/"
episode_hero_path: "/assets/img/stops/"
logo: "/assets/img/logo/utopie.png"
twitter_username: lucawyss
github_username:  lucawyss
menu_heading: "Selectionne une autre histoire :"
index_page_text: "Des habitants du quartier des Fougères-Le Vau ont voyagé dans le futur pour receuillir des histoires et nous raconter comment ça va être. Selectionne une piste sonore pour écouter les histoires du quartier !"
headphones_icon_color: "/assets/img/icons/headphones-dark.png"
headphones_icon_light: "/assets/img/icons/headphones-light.png"

# Build settings
markdown: kramdown
exclude:
  - Gemfile
  - Gemfile.lock

# Version settings (version number below is used for cache busting CSS and JS)
version_number: 1.0.0.1
